### ISSUE TITLE
ValueError: Export data fail

### ISSUE THREAD

**Issue by hackjustin** [jimmysitu/msfinance#1]
Hi Jimmy,

I'm getting the error noted in the title of this issue. Windows 10, python 3.

It looks like you're defining a random download_dir each time StockBase is initialized but not explicitly creating the directory. The result is that downloads are going to the default browser download folder, rather than download_dir, and the script fails.

https://github.com/jimmysitu/msfinance/blob/a8741391ef2c8777f216c339f5a7af50079037b1/msfinance/stocks.py#L52C18-L52C31

What do you think about giving the user the option to define the download location?

```python
stock = msf.Stock(
    debug=True, 
    session='xnas.db3',
    proxy=None,
    download_dir='whatever'
)
```

And perhaps dropping the PID from the path? Using a static location would allow the user can create the temp directory if it were missing for some reason.

https://github.com/jimmysitu/msfinance/blob/a8741391ef2c8777f216c339f5a7af50079037b1/msfinance/stocks.py#L52C18-L52C31

Change this
```python
self.download_dir = '/tmp/msfinance/' + str(os.getpid())
```
to this
```python
self.download_dir = '/tmp/msfinance/'
```

What do you think?

**Comment by jimmysitu** [comment]
@hackjustin ,  I try another way to init a temp dir for download storage. 
Just try this commit, 
[81572a6](https://github.com/jimmysitu/msfinance/commit/81572a653f5fa77791cfa1b00e24c5c21d900f20)
I do not have the python3 development env on a Windows machine, but I check it with github actions and it has already pass all tests under python3.9

**Comment by hackjustin** [comment]
@jimmysitu seems to be working now. I appreciate you working on this fix.
