### ISSUE TITLE
Automation is Impeded by 'Are you a robot' Check

### ISSUE THREAD

**Issue by wyattbradley34** [jimmysitu/msfinance#2]
Not sure if this is something you've had to deal with from MS but the current implementation doesn't account for the 'Are you a robot' check. I managed to come up with a workaround using debug=True and replacing line 85 in stocks.py with an input prompt telling the user to complete the puzzle.

**Comment by jimmysitu** [comment]
@wyattschwanbeck ,  it should be work now with [5609c1a](https://github.com/jimmysitu/msfinance/commit/5609c1adc69152ba530f9a52fadef3a4bc28119d)
Could you help me test it?

Thanks

**Comment by wyattbradley34** [comment]
Tested via the latest version and found the issue still persists. It may be necessary to keep debug mode on and essentially pause for a user to complete the puzzles needed to continue if you want to still use selenium to get the clean exports that MS provides. 
Alternatively, i did find method that just requires parsing tons and tons of performance IDs based on the ticker symbol. I don't know if morningstar regularly changes these performance IDs or even updates them for existing tickers but I managed to parse a bunch by manually updating the aws-waf token and using the public API key via the url:
`url = f"https://api-global.morningstar.com/sal-service/v1/stock/newfinancials/{performanceId}/{reportType}/detail?dataType=A&reportType=A&locale=en&languageId=en&locale=en&clientId=MDC&component=sal-equity-financials-details&version=4.30.0"`

It'd be cool if we could map all those performance IDs and figure out if they regularly change across all global ticker symbols. However, I'd also be happy to continue to test further iterations you should you find a way to get around those robot checks using selenium though.

Please keep me posted, Cheers!

**Comment by jimmysitu** [comment]
Hi, @wyattschwanbeck , I am quite sure the latest version on the github repo is ready to pass the robot test issue. Since it use undetected_chrome. It passed all actions test [here](https://github.com/jimmysitu/msfinance/actions/runs/11905500063)

Could you try to run the example script in the example dir to double confirm?

**Comment by wyattbradley34** [comment]
I tested it using the undetected_chrome driver instead of my default browser Firefox and can confirm it does function as intended! The issue still persists using firefox though and that's okay. You may want to let users know that they must use chrome instead of firefox in the docs. Thanks!
